version: "3.2"

services:
  gql_postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1234:5432

  gql_science_db_graphql_server:
    depends_on:
      - gql_postgres
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    # Await POSTGRES role and DB creation, migrate schema, then start web server:
    command: bash -C './migrateDbAndStartServer.sh'

  gql_ncbi_sim_srv:
    depends_on:
    - gql_postgres
    - gql_science_db_graphql_server
    build:
      context: .
      dockerfile: Dockerfile.ncbi_sim_srv
    ports:
        - "3344:3344"
    environment:
        PORT: 3344
        BASE_URL: /aminoAcidSequence
    command: npm start