version: "3.2"

services:
  gql_postgres2:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1235:5432

  gql_science_db_graphql_server2:
    depends_on:
      - gql_postgres2
    build:
      context: .
      dockerfile: Dockerfile.graphql_server

    volumes:
      - ./integration_test_run/instance2/schemas:/usr/src/app/schemas
      - ./integration_test_run/instance2/resolvers:/usr/src/app/resolvers
      - ./integration_test_run/instance2/models:/usr/src/app/models
      - ./integration_test_run/instance2/models-distributed:/usr/src/app/models-distributed
      - ./integration_test_run/instance2/models-webservice:/usr/src/app/models-webservice
      - ./integration_test_run/instance2/models-cenz-server:/usr/src/app/models-cenz-server
      - ./integration_test_run/instance2/migrations:/usr/src/app/migrations
      - ./integration_test_run/instance2/validations:/usr/src/app/validations
      - ./integration_test_run/instance2/patches:/usr/src/app/patches
      - ./sequelize_config.json:/usr/src/app/config/config.json

    ports:
      - "3030:3030"

    environment:
      PORT: 3030
      REQUIRE_SIGN_IN: "false"
      LIMIT_RECORDS: 25
    # Await POSTGRES role and DB creation, migrate schema, then start web server:
    networks:
     - integrationtest
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ./migrateDbAndStartServer.sh

    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start

networks:
  integrationtest:
    external: true