version: "3.2"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres

  science_db_graphql_server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    # Await POSTGRES role and DB creation (5s), migrate schema, then start web
    # server:
    command: >
      sh -c 'sleep 5 && ./node_modules/.bin/sequelize db:migrate && npm start'
