version: "3.2"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
     - 1234:5432

  science_db_graphql_server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    # TODO: It is better to wait for DB with /etc/init.d script on server
    # TODO: Change DB to Tests. Hint: NODE_ENV = 'development' || 'production' || 'test'
    command: >
      sh -c 'sleep 5 && ./node_modules/.bin/sequelize db:migrate && npm start'
