version: "3.2"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres

  science_db_graphql_server:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile.graphql_server
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    # Await POSTGRES role and DB creation, migrate schema, then start web
    # server:
    command: bash -C './migrateDbAndStartServer.sh'
